### ISSUE TITLE
How to copy properties?

### ISSUE THREAD

**Issue by samcov** [jacekkow/docker-gitblit#2]
I need to 

1. Turn on federation
2. Turn off auto https redirection and other things

How can I change properties?

**Comment by jacekkow** [comment]
Are you using Docker volumes (as in "Usage" section of README, not the "Local storage" option)?

If so, you can either find volume location (`docker volume ls`, `docker volume inspect VOLUMEID`) and modify gitblit.properties in proper directory, probably as root (`sudo` might be your friend). Remember to restart the container afterwards.

Of course you can also enter the container directly, install your favorite editor (nano, vim, emacs... Just use `apt update` + `apt install ...`) and edit `/opt/gitblit-data/gitblit.properties` directly.

**Comment by samcov** [comment]
You're the man!!!

I assumed that only the data would be in the volume, but there's everything I need right there.
![image](https://user-images.githubusercontent.com/1551314/114593788-581c7780-9c41-11eb-8de6-7415484fabf3.png)

**Comment by jacekkow** [comment]
Configuration is part of the "data" :)

Glad I could help.

**Comment by samcov** [comment]
BTW, I used the following docker-compose(**Thank You**):

version: '3.4'
 
services:
  gitblit:
    image: gitblit/gitblit:rpc
    container_name: gitblit
    ports:
      - "8443:8443"
      - "8180:8080"
      - "9418:9418"
      - "29418:29418"
    volumes:
      - ./gitblit-data:/var/opt/gitblit

**Comment by jacekkow** [comment]
Note that my container is `jacekkow/gitblit`, not `gitblit/gitblit`!

Fill issues related to that container to: https://github.com/gitblit/gitblit-docker

**Comment by samcov** [comment]
Yup, I had done this first, then found you later... switching!
